DROP TABLE IF EXISTS features;
DROP TABLE IF EXISTS feats;
DROP TABLE IF EXISTS spells;
DROP TABLE IF EXISTS backgrounds;
DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS subclasses;
DROP TABLE IF EXISTS classes;
